### PR TITLE
feat:  make percent_over return '' instead of None

### LINKED ISSUE #10: Replace None with empty string
In the report, inside Django Admin, when there's no data to show, `None` in being converted do `'None'`:

image

I think an empty string (`''`) would give us a better UI.

### PR DESCRIPTION
**Pull request by 11808s8**
Fixes https://github.com/cuducos/bot-followers/issues/10 ! :smile:

### CODE REVIEW

**Comment by cuducos** [comment]
Hi @11808s8, many thanks for jumping in!

Unfortunately, I'm afraid this solution is sub-optimal. It works, that's great… but I think we can re-think it before merging.

I would list three things to discuss here:

1. In the [Contributing](https://github.com/cuducos/bot-followers#contributing) session I ask contributors to format code with Black, but the CI says [your PR is failing in Black code style check](https://github.com/cuducos/bot-followers/pull/12/checks?check_run_id=367365977) — are you familiar with Black? Have you tried running it? How was the experience? Let me know so I can help you on that if needed ; )
2. I think the solution breaks the meaningfulness of the `Job.percent_over` API. This method was designed to _always_ return two values: the percentage and the error. This PR makes it returns just one (an empty string), so I think there's something about semantics left behind. I'm sorry this wasn't that clear in the current code, my bad.
3. I think the solution targets the wrong abstraction layer: in an high-level understanding of a model method that should return a percentage and the error, I understand that a return such as `None, None` is meaningful – it kind of says _I don't have enough data to calculate neither the percentage nor the error_. And I think this is fine as it is. On the other hand, the function `report` inside `admin.py` is the one in charge of transforming data from the model in something for the UI. I think that would be the perfect target to customize how to visualize the situation in which _no data_ should be transformed in an empty string. Does that make sense for you?

**Comment by 11808s8** [comment]
Hello @cuducos ! Thanks for the warm welcome hehehe.

Approaching the listed topics:

1. My bad! I ran Black only for the clone I made of your project directly into my coding environment and not for my fork! So that's that... (I ran it afterwards and it reformatted the appropriate file :D ).
2. This made my re-analyze the structure of the application from a new POV and made me better understand it. https://github.com/cuducos/bot-followers/pull/12/commits/dcdd23848d46e2d6c7900c2ed822fda1e58035e7 possibly deals with what was wrong in the last commit
3. Now it makes complete sense! I even changed it a bit to not show the plus/minus sign when nothing is returned from the humanized error... (0a8ffd9)

Any feedback is welcome!

**Comment by cuducos** [comment]
Many thanks, @11808s8, the over all solution looks way better now!

I would like to see two stylistic minor changes before merging, and rebase with `master`  to eliminate conflicts. I can do all that, I really don't mind, but let me know what you prefer (maybe you want to do it yourself).

Regarding dcdd238, I would keep the early `return` (instead of two indented blocks, one under `if` and another under `else`), following the [flat success path](https://www.vinta.com.br/blog/2018/flat-success-path/) design.

Regarding 0a8ffd9 I would avoid too many string concatenation with `+` and use f-string instead. It's sort of a new recommended standard and perform better.

**Comment by 11808s8** [comment]
Hey @cuducos I just saw the PR was merged but I didn't fix what you commented yet! :(( . I'll open a PR soon with the fixes from the advices you gave me (greatly appreciated <3). Just didn't got around to do it yet ~(so much stuff, so little time hehehe)~

**Comment by cuducos** [comment]
Sem problemas! Eu estava mexendo na biblioteca e fiz as alterações, tu pode olhar os _commits_ na `master` pode ver q q fiz e tal ; )

**Pull request merged**
